config/routes.rb
CoachingCarousel::Application.routes.draw do
  resources :source_data_pfrs

  resources :coach_employments

  resources :teams

  resources :coaches

  

end

app/models/coach_employment.rb
class CoachEmployment < ActiveRecord::Base
  belongs_to :coach
  belongs_to :team

  def coach_name
    self.coach.name
  end

  def team_name
    self.team.name
  end
end

app/controllers/coach_employments_controller.rb
class CoachEmploymentsController < ApplicationController
  before_action :set_coach_employment, only: [:show, :edit, :update, :destroy]

  # GET /coach_employments
  # GET /coach_employments.json
  def index
    @coach_employments = CoachEmployment.all.
      includes(:coach, :team).
      where("year >= 1973").
      order("coaches.name,year")

    respond_to do |format|
      format.html  { render :action => "index" }
      format.json  { render :json => @coach_employments.as_json(
                    :methods => [:coach_name, :team_name]
                )}
    end
  end

  # GET /coach_employments/1
  # GET /coach_employments/1.json
  def show
  end

  # GET /coach_employments/new
  def new
    @coach_employment = CoachEmployment.new
  end

  # GET /coach_employments/1/edit
  def edit
  end

  # POST /coach_employments
  # POST /coach_employments.json
  def create
    @coach_employment = CoachEmployment.new(coach_employment_params)

    respond_to do |format|
      if @coach_employment.save
        format.html { redirect_to @coach_employment, notice: 'Coach employment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @coach_employment }
      else
        format.html { render action: 'new' }
        format.json { render json: @coach_employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /coach_employments/1
  # PATCH/PUT /coach_employments/1.json
  def update
    respond_to do |format|
      if @coach_employment.update(coach_employment_params)
        format.html { redirect_to @coach_employment, notice: 'Coach employment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @coach_employment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /coach_employments/1
  # DELETE /coach_employments/1.json
  def destroy
    @coach_employment.destroy
    respond_to do |format|
      format.html { redirect_to coach_employments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coach_employment
      @coach_employment = CoachEmployment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coach_employment_params
      params.require(:coach_employment).permit(:coach_id, :team_id, :year, :role, :age)
    end
end

app/helpers/coach_employments_helper.rb
module CoachEmploymentsHelper
end

app/views/coach_employments/_form.html.erb
<%= form_for(@coach_employment) do |f| %>
  <% if @coach_employment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@coach_employment.errors.count, "error") %> prohibited this coach_employment from being saved:</h2>

      <ul>
      <% @coach_employment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :coach_id %><br>
    <%= f.number_field :coach_id %>
  </div>
  <div class="field">
    <%= f.label :team_id %><br>
    <%= f.number_field :team_id %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/coach_employments/edit.html.erb
<h1>Editing coach_employment</h1>

<%= render 'form' %>

<%= link_to 'Show', @coach_employment %> |
<%= link_to 'Back', coach_employments_path %>

app/views/coach_employments/index.html.erb
<h1>Listing coach_employments</h1>

<table>
  <thead>
    <tr>
      <th>Coach</th>
      <th>Team</th>
      <th>Year</th>
      <th>Role</th>
      <th>Age</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @coach_employments.each do |coach_employment| %>
      <tr>
        <td><%= coach_employment.coach.name %></td>
        <td><%= coach_employment.team.name %></td>
        <td><%= coach_employment.year %></td>
        <td><%= coach_employment.role %></td>
        <td><%= coach_employment.age %></td>
        <td><%= link_to 'Show', coach_employment %></td>
        <td><%= link_to 'Edit', edit_coach_employment_path(coach_employment) %></td>
        <td><%= link_to 'Destroy', coach_employment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coach employment', new_coach_employment_path %>

app/views/coach_employments/new.html.erb
<h1>New coach_employment</h1>

<%= render 'form' %>

<%= link_to 'Back', coach_employments_path %>

app/views/coach_employments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Coach:</strong>
  <%= @coach_employment.coach_id %>
</p>

<p>
  <strong>Team:</strong>
  <%= @coach_employment.team_id %>
</p>

<p>
  <strong>Year:</strong>
  <%= @coach_employment.year %>
</p>

<p>
  <strong>Role:</strong>
  <%= @coach_employment.role %>
</p>

<p>
  <strong>Age:</strong>
  <%= @coach_employment.age %>
</p>

<%= link_to 'Edit', edit_coach_employment_path(@coach_employment) %> |
<%= link_to 'Back', coach_employments_path %>