config/routes.rb
CoachingCarousel::Application.routes.draw do
  resources :source_data_pfrs

  resources :coach_employments

  resources :teams

  resources :coaches

  

end

app/models/source_data_pfr.rb
class SourceDataPfr < ActiveRecord::Base
end

app/controllers/source_data_pfrs_controller.rb
class SourceDataPfrsController < ApplicationController
  before_action :set_source_data_pfr, only: [:show, :edit, :update, :destroy]

  # GET /source_data_pfrs
  # GET /source_data_pfrs.json
  def index
    @source_data_pfrs = SourceDataPfr.all
  end

  # GET /source_data_pfrs/1
  # GET /source_data_pfrs/1.json
  def show
  end

  # GET /source_data_pfrs/new
  def new
    @source_data_pfr = SourceDataPfr.new
  end

  # GET /source_data_pfrs/1/edit
  def edit
  end

  # POST /source_data_pfrs
  # POST /source_data_pfrs.json
  def create
    @source_data_pfr = SourceDataPfr.new(source_data_pfr_params)

    respond_to do |format|
      if @source_data_pfr.save
        format.html { redirect_to @source_data_pfr, notice: 'Source data pfr was successfully created.' }
        format.json { render action: 'show', status: :created, location: @source_data_pfr }
      else
        format.html { render action: 'new' }
        format.json { render json: @source_data_pfr.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /source_data_pfrs/1
  # PATCH/PUT /source_data_pfrs/1.json
  def update
    respond_to do |format|
      if @source_data_pfr.update(source_data_pfr_params)
        format.html { redirect_to @source_data_pfr, notice: 'Source data pfr was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @source_data_pfr.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /source_data_pfrs/1
  # DELETE /source_data_pfrs/1.json
  def destroy
    @source_data_pfr.destroy
    respond_to do |format|
      format.html { redirect_to source_data_pfrs_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_source_data_pfr
      @source_data_pfr = SourceDataPfr.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def source_data_pfr_params
      params.require(:source_data_pfr).permit(:coach, :year, :age, :level, :employer, :role)
    end
end

app/helpers/source_data_pfrs_helper.rb
module SourceDataPfrsHelper
end

app/views/source_data_pfrs/_form.html.erb
<%= form_for(@source_data_pfr) do |f| %>
  <% if @source_data_pfr.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@source_data_pfr.errors.count, "error") %> prohibited this source_data_pfr from being saved:</h2>

      <ul>
      <% @source_data_pfr.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :coach %><br>
    <%= f.text_field :coach %>
  </div>
  <div class="field">
    <%= f.label :year %><br>
    <%= f.number_field :year %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :level %><br>
    <%= f.text_field :level %>
  </div>
  <div class="field">
    <%= f.label :employer %><br>
    <%= f.text_field :employer %>
  </div>
  <div class="field">
    <%= f.label :role %><br>
    <%= f.text_field :role %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/source_data_pfrs/edit.html.erb
<h1>Editing source_data_pfr</h1>

<%= render 'form' %>

<%= link_to 'Show', @source_data_pfr %> |
<%= link_to 'Back', source_data_pfrs_path %>

app/views/source_data_pfrs/index.html.erb
<h1>Listing source_data_pfrs</h1>

<table>
  <thead>
    <tr>
      <th>Coach</th>
      <th>Year</th>
      <th>Age</th>
      <th>Level</th>
      <th>Employer</th>
      <th>Role</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @source_data_pfrs.each do |source_data_pfr| %>
      <tr>
        <td><%= source_data_pfr.coach %></td>
        <td><%= source_data_pfr.year %></td>
        <td><%= source_data_pfr.age %></td>
        <td><%= source_data_pfr.level %></td>
        <td><%= source_data_pfr.employer %></td>
        <td><%= source_data_pfr.role %></td>
        <td><%= link_to 'Show', source_data_pfr %></td>
        <td><%= link_to 'Edit', edit_source_data_pfr_path(source_data_pfr) %></td>
        <td><%= link_to 'Destroy', source_data_pfr, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Source data pfr', new_source_data_pfr_path %>

app/views/source_data_pfrs/new.html.erb
<h1>New source_data_pfr</h1>

<%= render 'form' %>

<%= link_to 'Back', source_data_pfrs_path %>

app/views/source_data_pfrs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Coach:</strong>
  <%= @source_data_pfr.coach %>
</p>

<p>
  <strong>Year:</strong>
  <%= @source_data_pfr.year %>
</p>

<p>
  <strong>Age:</strong>
  <%= @source_data_pfr.age %>
</p>

<p>
  <strong>Level:</strong>
  <%= @source_data_pfr.level %>
</p>

<p>
  <strong>Employer:</strong>
  <%= @source_data_pfr.employer %>
</p>

<p>
  <strong>Role:</strong>
  <%= @source_data_pfr.role %>
</p>

<%= link_to 'Edit', edit_source_data_pfr_path(@source_data_pfr) %> |
<%= link_to 'Back', source_data_pfrs_path %>